### PR TITLE
Task 8

### PR DESCRIPTION
**Pull request by EDovgalo**

### CODE REVIEW

**Comment by sulemanof** [comment]
Is it ready for review?

**Comment by EDovgalo** [comment]
> Is it ready for review?

Yes

**Review by sulemanof — CHANGES_REQUESTED** [review]
Please, check the next requirements (which are not working):
-  When new user enters the site using direct link with search parameters – show search results
- By default, user lands on a new
page with empty results page

Routing is not working when dynamically changed:
- select any movie details
- select another movie details
- go back in browser history
- expected - the previous movie details renderer

routing

**Comment by EDovgalo** [comment]
> Please, check the next requirements (which are not working):
> 
> * When new user enters the site using direct link with search parameters – show search results
> * By default, user lands on a new
>   page with empty results page
> 
> Routing is not working when dynamically changed:
> 
> * select any movie details
> * select another movie details
> * go back in browser history
> * expected - the previous movie details renderer
> 
> routing

Fixed

**Review by sulemanof — CHANGES_REQUESTED** [review]
- Clicking the search button on movie details page is not working:

  image

- sorting is not working

  image

- `MovieSection` component loads both at both pages:
  
  image

the best way would be to load it only once. Could you please check if it is reachable

**Comment by EDovgalo** [comment]
> * Clicking the search button on movie details page is not working:
>   image
> * sorting is not working
>   image
> * `MovieSection` component loads both at both pages:
>   image
> 
> the best way would be to load it only once. Could you please check if it is reachable
i have doubt about my solution. Can you review and suggest your solution


> the best way would be to load it only once. Could you please check if it is reachable

i have doubt about my solution. Can you review and suggest your solution

> * Clicking the search button on movie details page is not working:
>   image
> * sorting is not working
>   image
> * `MovieSection` component loads both at both pages:
>   image
> 
> the best way would be to load it only once. Could you please check if it is reachable

1) done
2) done
3) done. I have doubt about my solution. Can you review and suggest your solution

**Review by sulemanof — APPROVED** [review]
Looks good now, checked out locally

**Pull request merged**
